service: checkin-report
app: tiktrack
org: siamraj

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # you can define service wide environment variables here
  environment:
    DB_HOST: ${param:DB_HOST}
    DB_USER: ${param:DB_USER}
    DB_PASS: ${param:DB_PASS}
    DB_NAME: ${param:DB_NAME}
    MAIL_USER: ${param:MAIL_USER}
    MAIL_PASS: ${param:MAIL_PASS}

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  notify:
    handler: handler.notify
    timeout: 60
    events:
      - schedule: cron(0 5 ? JUL,AUG MON-FRI 2021)
